name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Publish
        run: |
          yarn
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
